### ISSUE TITLE
Improve the design?

### ISSUE THREAD

**Issue by gargullia** [SalaniLeo/Forecast#1]
Increase the number of temperatures and add graphs, there is an app on the mac https://frankbyte.com/weather

You can make a chart here https://gitlab.gnome.org/World/elastic
https://developer.gnome.org/hig/index.html

**Comment by SalaniLeo** [comment]
I think the design is now much better. I still have to add graphs, but i'll create a separate page for that. For now I'll leave this issue open, if you have some other ideas feel free to tell me.

**Comment by SalaniLeo** [comment]
With release v0.2.2 I've redesign the app to be more like the old Meteo, and in the next release I'll add more detailed info + graphs, so this issue is resolved
