### ISSUE TITLE
Small papercuts in UI

### ISSUE THREAD

**Issue by ghost** [SalaniLeo/Forecast#11]
City name + Sky Value seems not translated.

https://github.com/SalaniLeo/Forecast/blob/master/Forecast/WttrInfo.py#L251

![title](https://github.com/SalaniLeo/Forecast/assets/6218679/72ef12d9-34ef-400c-a1ed-d617b9d8e2fe)

Units entry seems not translatable.

https://github.com/SalaniLeo/Forecast/blob/master/Forecast/App.py#L23

![unit](https://github.com/SalaniLeo/Forecast/assets/6218679/2d35a8fd-e683-4b60-a289-0f6bf631159b)

Also Personal API area seems too narrow.

**Comment by SalaniLeo** [comment]
This issues are all solved in release v0.2.2
