### ISSUE TITLE
Light text on light background

### ISSUE THREAD

**Issue by StuieT85** [SalaniLeo/Forecast#13]
Is it possible to change the text colour to a darker colour if the weather is particularly bright, as the lack of contrast makes it difficult to read?
![Screenshot from 2023-06-19 09-00-36](https://github.com/SalaniLeo/Forecast/assets/46073353/099b179d-9dde-4178-87bd-0329e0fbc732)

Other than that, I love the app :)

**Comment by SalaniLeo** [comment]
I added the dark text on light backgrounds, thanks for the suggestion!
