### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by hsbasu** [SalaniLeo/Forecast#14]
Hi! This is a beautiful app. But It does not provide a debian package yet. Do you have any plans for that?

I already have created a debian package. But for that the code had to be modified a bit. So, if needed I can create a PR in no time.

https://github.com/hsbasu/Forecast/tree/mod-for-debian

https://github.com/hsbasu/Forecast/tree/deb-packaging

**Comment by SalaniLeo** [comment]
Thanks for the help, I'll include everything so that in the next release there will also be a Debian package

**Comment by hsbasu** [comment]
Hi! There is a chance that after merging #15, flatpak packages are not working properly. So, please test the PR first before merging. I faced similar issues while creating snap package for one of my apps.

**Comment by SalaniLeo** [comment]
Flatpak works fine for me, thanks for the heads-up
