### ISSUE TITLE
Help with translation into Russian

### ISSUE THREAD

**Issue by Armatik** [SalaniLeo/Forecast#19]
Hello, can I help you with translating the application into Russian?

**Comment by SalaniLeo** [comment]
Absolutely! Any help or translation is very appreciated!

**Comment by Armatik** [comment]
> Absolutely! Any help or translation is very appreciated!

Does Forecast have a separate file containing the entire text of the application or are all text fields set in the code?

**Comment by SalaniLeo** [comment]
No, they are all set in the code, but in the Forecast.pot file you can find all strings to translate

**Comment by Armatik** [comment]
> No, they are all set in the code, but in the Forecast.pot file you can find all strings to translate

Okay, thanks.

**Comment by Armatik** [comment]
> No, they are all set in the code, but in the Forecast.pot file you can find all strings to translate

Send PR.
