### ISSUE TITLE
Works too slow

### ISSUE THREAD

**Issue by radical4ever** [SalaniLeo/Forecast#2]
Hi, i love that this new succession of meteo, but to me it is pretty slow on searching locations, so maybe is something related to python idk, but thanks anyways to redevelop the app!!

**Comment by SalaniLeo** [comment]
yes, I know. I'm working on updating the way it searches for locations and also adding a lot more data as requested by #1, but now I don't have that much time. I'll update it as soon as I can.

**Comment by SalaniLeo** [comment]
Searching cities should be a lot quicker now thanks to #3, at least for me it is. I'll close the issue for now

**Comment by Mek101** [comment]
#3 only makes the displaying quicker as it went from `N^2` to `N` elements, the search itself isn't touched as it's basically a raw http call
