### ISSUE TITLE
Adding a more detailed weather forecast for the next five days

### ISSUE THREAD

**Issue by Armatik** [SalaniLeo/Forecast#22]
I suggest adding a more detailed hourly forecast for five days, using an example of how it is implemented for today. To do this, I propose to logically divide the application window into two parts: Today and the Five-day forecast. This will make it more convenient to compose the elements (I will attach an approximate layout of the idea a little later). I also consider it necessary to add the ability to adjust the color (lighter or darker) of the glass substrates under the elements.

**Comment by SalaniLeo** [comment]
Thanks for the suggestions, I already added a more detailed five days page, but I still have to release a new version with that. I'm very busy this month for personal reasons so I can't guarantee when I'll release a new version. To use that feature you can clone the repo and start the app using __init__.py. Regarding the other suggestion I'll add it whenever I can.

**Comment by SalaniLeo** [comment]
While I was trying to figure out why my app was crashing I stumbled across this [gtk issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/5917) and it was the cause. I explainded in #25 everything
