### ISSUE TITLE
Waiting for newer version of gtk for new release

### ISSUE THREAD

**Issue by SalaniLeo** [SalaniLeo/Forecast#25]
Hi all, first thanks for using my app. There is currently a bug with GTK [5917](https://gitlab.gnome.org/GNOME/gtk/-/issues/5917) which makes an app crash when removing an element from a Gtk.Stack linked with a Gtk.StackSidebar, and the problem is I already wrote the code for a more accurate forecast page which uses exactly that (and besides snap support is the only major addition, also it's too late to remove the new code). I made the decision to wait for a newer release of gtk that would resolve the bug to release a new version. I'm very sorry for the wait, it's not my fault.

**Comment by SalaniLeo** [comment]
after 6 month gtk still crashes... 
Still waiting for this issue to be resolved

**Comment by soumyaDghosh** [comment]
Hi @SalaniLeo the recent rework has completely removed the snap support. Kindly revert that. Thank you.
