### ISSUE TITLE
Merge similar locations

### ISSUE THREAD

**Issue by Mek101** [SalaniLeo/Forecast#3]
![Schermata del 2023-06-02 18-53-21](https://github.com/SalaniLeo/Forecast/assets/34246799/80cc3079-c9bc-4fff-abd6-48dbcbae9ee4)

Apparently whatever API(s) you're using result in duplicates. If I have to take a guess, it could be caused by the different rows only differing by a few decimals. Perhaps add filter which removes the entries less than 0.001 apart?

**Comment by SalaniLeo** [comment]
Thanks! Or should I say grazie :)

**Comment by Mek101** [comment]
Di niente uomo :+1:
