### ISSUE TITLE
Uses UTC instead of the local timezone

### ISSUE THREAD

**Issue by nekohayo** [SalaniLeo/Forecast#32]
Running the app from flathub, it seems that it uses UTC (ex: `02:54`) instead of using the system's local time (ex: `22:54`):

![image](https://github.com/SalaniLeo/Forecast/assets/479401/4525bc3a-37d9-42e4-b5c4-8a103706a19e)

By the way, it might be worth being explicit with that label, and prefixing it with `Last checked on `; maybe you could even put the refresh button directly next to that label?

**Comment by SalaniLeo** [comment]
Hey, thanks for all your issues, I will try to fix them as soon as I can!
