### ISSUE TITLE
Weekly forecast chart breaks (cut off portions) under some conditions

### ISSUE THREAD

**Issue by nekohayo** [SalaniLeo/Forecast#33]
I'm not sure how to explain this, but if you look at the temperature ranges bars shown in this screenshot's "Weekly forecast" section:

![image](https://github.com/SalaniLeo/Forecast/assets/479401/1cbdb79f-4571-43e2-8bc3-32b43f8e5eb1)

...you will see that the bar for Friday is cut off on the left side.

Similarly here, on the Monday row:

![image](https://github.com/SalaniLeo/Forecast/assets/479401/ba7a0555-e828-410b-a08b-1825ad4bc535)

This is the flatpak version running on GNOME 45 with 1.00 font scaling.

**Comment by SalaniLeo** [comment]
this is going to be solved in #40
