### ISSUE TITLE
Better app listing

### ISSUE THREAD

**Issue by bertob** [SalaniLeo/Forecast#36]
This app's listing already looks pretty good, with just a few tweaks it could pass the [Flathub metadata guidelines](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines), which would make it eligible to be featured.

The issues are:
- The summary "⛅ Weather app for Linux made in LibAdwaita" is too long and a bit odd. Something simple that doesn't get into technical details, such as "Check the weather" would be better.
- The app needs brand colors https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#brand-colors
- The screenshot has non-default window decorations (should be close-only)

**Comment by SalaniLeo** [comment]
This will be resolved in #40 alongside other bugs

**Comment by bertob** [comment]
> ⛅ Check the weather! 

This still doesn't meet the Flathub guidelines, in particular the one about non-standard formatting (the emoji and exclamation mark).

The MR also doesn't seem to change the screenshots or add brand colors, so unless that done somewhere else I think most of the stuff from the issue above still applies.
