### ISSUE TITLE
Incorrect text aligment 

### ISSUE THREAD

**Issue by Mek101** [SalaniLeo/Forecast#6]
![Schermata del 2023-06-02 23-48-55](https://github.com/SalaniLeo/Forecast/assets/34246799/601e26b1-6a01-4a60-b032-41ebc6b6a8c8)

The "Wind" row isn't properly aligned. Not sure much can be done about it without involving the GTK toolkit, as in the source code it's correctly aligned to the number of characters.

The misalignment is likely caused by the font not being monospace, but with different characters having different widths.

**Comment by SalaniLeo** [comment]
is it still misaligned?

**Comment by Mek101** [comment]
![Schermata del 2023-06-05 20-08-46](https://github.com/SalaniLeo/Forecast/assets/34246799/2b0dd352-5bac-44cd-9d82-bd6b42994338)
Pare di sì

**Comment by SalaniLeo** [comment]
non so perchè io anche scrivendo le stesse cose che hai tu non riesco a replicare sto problema. Come pensi che si possa risolvere?

**Comment by SalaniLeo** [comment]
Penso sia perchè cambia il font ma non so come risolverlo, dovrei metterne uno fisso ma poi non rispetta quello di sistema

**Comment by SalaniLeo** [comment]
I fixed this problem using two different labels for the data and names. This issue is now solved
