### ISSUE TITLE
[Feature Request] Intagrate location into quick access like the offical gnome weather app?

### ISSUE THREAD

**Issue by SharkPlush** [SalaniLeo/Forecast#8]
![Screenshot from 2023-06-05 11-54-30](https://github.com/SalaniLeo/Forecast/assets/86890204/d6723240-0d2a-4f28-86cb-467139e80052)
 
This is what I mean

**Comment by SalaniLeo** [comment]
From what I read online you need to use javascript or an extension to integrate an app inside the gnome shell, and since my app is in python I think it's not possible. I may be wrong tho, so feel free to correct me
